import os
import numpy as np
import tempfile, zipfile
import torch
import torch.nn as nn
import torch.nn.functional as F
try:
    import torchvision
    import torchaudio
except:
    pass

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        self.conv0_conv = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=4, kernel_size=(3,3), out_channels=16, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.conv0_relu = nn.ReLU()
        self.enc1_0_proj_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=16, in_channels=16, kernel_size=(3,3), out_channels=16, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.enc1_0_proj_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc1_0_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=16, in_channels=16, kernel_size=(3,3), out_channels=16, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.enc1_0_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(1,1), out_channels=8, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc1_0_conv1_relu = nn.ReLU()
        self.enc1_0_conv2_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=8, in_channels=8, kernel_size=(3,3), out_channels=8, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.enc1_0_conv2_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=8, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc1_0_relu = nn.ReLU()
        self.enc1_1_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.enc1_1_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=8, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc1_1_conv1_relu = nn.ReLU()
        self.enc1_1_conv2_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=8, in_channels=8, kernel_size=(3,3), out_channels=8, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.enc1_1_conv2_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=8, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc1_1_relu = nn.ReLU()
        self.enc2_0_proj_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.enc2_0_proj_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc2_0_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.enc2_0_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=8, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc2_0_conv1_relu = nn.ReLU()
        self.enc2_0_conv2_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=8, in_channels=8, kernel_size=(3,3), out_channels=8, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.enc2_0_conv2_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=8, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc2_0_relu = nn.ReLU()
        self.enc2_1_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.enc2_1_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=8, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc2_1_conv1_relu = nn.ReLU()
        self.enc2_1_conv2_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=8, in_channels=8, kernel_size=(3,3), out_channels=8, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.enc2_1_conv2_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=8, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc2_1_relu = nn.ReLU()
        self.enc3_0_proj_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.enc3_0_proj_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc3_0_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(2,2))
        self.enc3_0_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=8, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc3_0_conv1_relu = nn.ReLU()
        self.enc3_0_conv2_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=8, in_channels=8, kernel_size=(3,3), out_channels=8, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.enc3_0_conv2_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=8, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc3_0_relu = nn.ReLU()
        self.enc3_1_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.enc3_1_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=8, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc3_1_conv1_relu = nn.ReLU()
        self.enc3_1_conv2_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=8, in_channels=8, kernel_size=(3,3), out_channels=8, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.enc3_1_conv2_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=8, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.enc3_1_relu = nn.ReLU()
        self.encdec_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.encdec_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.encdec_relu = nn.ReLU()
        self.dec1_decode_conv_conv0_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.dec1_decode_conv_conv0_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec1_decode_conv_conv0_relu = nn.ReLU()
        self.dec1_decode_conv_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.dec1_decode_conv_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec1_upsample_0 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec1_upsample_1 = nn.Upsample(align_corners=False, mode='bilinear', scale_factor=(2.0,2.0), size=None)
        self.dec1_proj_conv_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.dec1_proj_conv_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec1_proj_conv_relu = nn.ReLU()
        self.dec2_decode_conv_conv0_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.dec2_decode_conv_conv0_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec2_decode_conv_conv0_relu = nn.ReLU()
        self.dec2_decode_conv_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.dec2_decode_conv_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec2_upsample_0 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=16, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec2_upsample_1 = nn.Upsample(align_corners=False, mode='bilinear', scale_factor=(2.0,2.0), size=None)
        self.dec2_proj_conv_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=32, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.dec2_proj_conv_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=16, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec2_proj_conv_relu = nn.ReLU()
        self.dec3_decode_conv_conv0_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=16, in_channels=16, kernel_size=(3,3), out_channels=16, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.dec3_decode_conv_conv0_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(1,1), out_channels=16, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec3_decode_conv_conv0_relu = nn.ReLU()
        self.dec3_decode_conv_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=16, in_channels=16, kernel_size=(3,3), out_channels=16, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.dec3_decode_conv_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(1,1), out_channels=16, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec3_upsample_0 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(1,1), out_channels=16, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec3_upsample_1 = nn.Upsample(align_corners=False, mode='bilinear', scale_factor=(2.0,2.0), size=None)
        self.dec3_proj_conv_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=16, in_channels=16, kernel_size=(3,3), out_channels=16, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.dec3_proj_conv_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(1,1), out_channels=16, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.dec3_proj_conv_relu = nn.ReLU()
        self.out0_conv0_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=16, in_channels=16, kernel_size=(3,3), out_channels=16, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.out0_conv0_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(1,1), out_channels=16, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.out0_conv0_relu = nn.ReLU()
        self.out0_conv1_depthwise = nn.Conv2d(bias=False, dilation=(1,1), groups=16, in_channels=16, kernel_size=(3,3), out_channels=16, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.out0_conv1_pointwise = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(1,1), out_channels=16, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.out1_conv = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=16, kernel_size=(3,3), out_channels=4, padding=(1,1), padding_mode='zeros', stride=(1,1))

        archive = zipfile.ZipFile('HuanKSigma.pnnx.bin', 'r')
        self.conv0_conv.bias = self.load_pnnx_bin_as_parameter(archive, 'conv0.conv.bias', (16), 'float32')
        self.conv0_conv.weight = self.load_pnnx_bin_as_parameter(archive, 'conv0.conv.weight', (16,4,3,3), 'float32')
        self.enc1_0_proj_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.0.proj.depthwise.weight', (16,1,3,3), 'float32')
        self.enc1_0_proj_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc1.0.proj.pointwise.bias', (32), 'float32')
        self.enc1_0_proj_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.0.proj.pointwise.weight', (32,16,1,1), 'float32')
        self.enc1_0_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.0.conv1.depthwise.weight', (16,1,3,3), 'float32')
        self.enc1_0_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc1.0.conv1.pointwise.bias', (8), 'float32')
        self.enc1_0_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.0.conv1.pointwise.weight', (8,16,1,1), 'float32')
        self.enc1_0_conv2_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.0.conv2.depthwise.weight', (8,1,3,3), 'float32')
        self.enc1_0_conv2_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc1.0.conv2.pointwise.bias', (32), 'float32')
        self.enc1_0_conv2_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.0.conv2.pointwise.weight', (32,8,1,1), 'float32')
        self.enc1_1_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.1.conv1.depthwise.weight', (32,1,3,3), 'float32')
        self.enc1_1_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc1.1.conv1.pointwise.bias', (8), 'float32')
        self.enc1_1_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.1.conv1.pointwise.weight', (8,32,1,1), 'float32')
        self.enc1_1_conv2_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.1.conv2.depthwise.weight', (8,1,3,3), 'float32')
        self.enc1_1_conv2_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc1.1.conv2.pointwise.bias', (32), 'float32')
        self.enc1_1_conv2_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc1.1.conv2.pointwise.weight', (32,8,1,1), 'float32')
        self.enc2_0_proj_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.0.proj.depthwise.weight', (32,1,3,3), 'float32')
        self.enc2_0_proj_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc2.0.proj.pointwise.bias', (32), 'float32')
        self.enc2_0_proj_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.0.proj.pointwise.weight', (32,32,1,1), 'float32')
        self.enc2_0_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.0.conv1.depthwise.weight', (32,1,3,3), 'float32')
        self.enc2_0_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc2.0.conv1.pointwise.bias', (8), 'float32')
        self.enc2_0_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.0.conv1.pointwise.weight', (8,32,1,1), 'float32')
        self.enc2_0_conv2_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.0.conv2.depthwise.weight', (8,1,3,3), 'float32')
        self.enc2_0_conv2_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc2.0.conv2.pointwise.bias', (32), 'float32')
        self.enc2_0_conv2_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.0.conv2.pointwise.weight', (32,8,1,1), 'float32')
        self.enc2_1_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.1.conv1.depthwise.weight', (32,1,3,3), 'float32')
        self.enc2_1_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc2.1.conv1.pointwise.bias', (8), 'float32')
        self.enc2_1_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.1.conv1.pointwise.weight', (8,32,1,1), 'float32')
        self.enc2_1_conv2_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.1.conv2.depthwise.weight', (8,1,3,3), 'float32')
        self.enc2_1_conv2_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc2.1.conv2.pointwise.bias', (32), 'float32')
        self.enc2_1_conv2_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc2.1.conv2.pointwise.weight', (32,8,1,1), 'float32')
        self.enc3_0_proj_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.0.proj.depthwise.weight', (32,1,3,3), 'float32')
        self.enc3_0_proj_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc3.0.proj.pointwise.bias', (32), 'float32')
        self.enc3_0_proj_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.0.proj.pointwise.weight', (32,32,1,1), 'float32')
        self.enc3_0_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.0.conv1.depthwise.weight', (32,1,3,3), 'float32')
        self.enc3_0_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc3.0.conv1.pointwise.bias', (8), 'float32')
        self.enc3_0_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.0.conv1.pointwise.weight', (8,32,1,1), 'float32')
        self.enc3_0_conv2_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.0.conv2.depthwise.weight', (8,1,3,3), 'float32')
        self.enc3_0_conv2_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc3.0.conv2.pointwise.bias', (32), 'float32')
        self.enc3_0_conv2_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.0.conv2.pointwise.weight', (32,8,1,1), 'float32')
        self.enc3_1_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.1.conv1.depthwise.weight', (32,1,3,3), 'float32')
        self.enc3_1_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc3.1.conv1.pointwise.bias', (8), 'float32')
        self.enc3_1_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.1.conv1.pointwise.weight', (8,32,1,1), 'float32')
        self.enc3_1_conv2_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.1.conv2.depthwise.weight', (8,1,3,3), 'float32')
        self.enc3_1_conv2_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'enc3.1.conv2.pointwise.bias', (32), 'float32')
        self.enc3_1_conv2_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'enc3.1.conv2.pointwise.weight', (32,8,1,1), 'float32')
        self.encdec_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'encdec.depthwise.weight', (32,1,3,3), 'float32')
        self.encdec_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'encdec.pointwise.bias', (32), 'float32')
        self.encdec_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'encdec.pointwise.weight', (32,32,1,1), 'float32')
        self.dec1_decode_conv_conv0_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec1.decode_conv.conv0.depthwise.weight', (32,1,3,3), 'float32')
        self.dec1_decode_conv_conv0_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'dec1.decode_conv.conv0.pointwise.bias', (32), 'float32')
        self.dec1_decode_conv_conv0_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec1.decode_conv.conv0.pointwise.weight', (32,32,1,1), 'float32')
        self.dec1_decode_conv_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec1.decode_conv.conv1.depthwise.weight', (32,1,3,3), 'float32')
        self.dec1_decode_conv_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'dec1.decode_conv.conv1.pointwise.bias', (32), 'float32')
        self.dec1_decode_conv_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec1.decode_conv.conv1.pointwise.weight', (32,32,1,1), 'float32')
        self.dec1_upsample_0.bias = self.load_pnnx_bin_as_parameter(archive, 'dec1.upsample.0.bias', (32), 'float32')
        self.dec1_upsample_0.weight = self.load_pnnx_bin_as_parameter(archive, 'dec1.upsample.0.weight', (32,32,1,1), 'float32')
        self.dec1_proj_conv_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec1.proj_conv.depthwise.weight', (32,1,3,3), 'float32')
        self.dec1_proj_conv_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'dec1.proj_conv.pointwise.bias', (32), 'float32')
        self.dec1_proj_conv_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec1.proj_conv.pointwise.weight', (32,32,1,1), 'float32')
        self.dec2_decode_conv_conv0_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec2.decode_conv.conv0.depthwise.weight', (32,1,3,3), 'float32')
        self.dec2_decode_conv_conv0_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'dec2.decode_conv.conv0.pointwise.bias', (32), 'float32')
        self.dec2_decode_conv_conv0_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec2.decode_conv.conv0.pointwise.weight', (32,32,1,1), 'float32')
        self.dec2_decode_conv_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec2.decode_conv.conv1.depthwise.weight', (32,1,3,3), 'float32')
        self.dec2_decode_conv_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'dec2.decode_conv.conv1.pointwise.bias', (32), 'float32')
        self.dec2_decode_conv_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec2.decode_conv.conv1.pointwise.weight', (32,32,1,1), 'float32')
        self.dec2_upsample_0.bias = self.load_pnnx_bin_as_parameter(archive, 'dec2.upsample.0.bias', (16), 'float32')
        self.dec2_upsample_0.weight = self.load_pnnx_bin_as_parameter(archive, 'dec2.upsample.0.weight', (16,32,1,1), 'float32')
        self.dec2_proj_conv_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec2.proj_conv.depthwise.weight', (32,1,3,3), 'float32')
        self.dec2_proj_conv_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'dec2.proj_conv.pointwise.bias', (16), 'float32')
        self.dec2_proj_conv_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec2.proj_conv.pointwise.weight', (16,32,1,1), 'float32')
        self.dec3_decode_conv_conv0_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec3.decode_conv.conv0.depthwise.weight', (16,1,3,3), 'float32')
        self.dec3_decode_conv_conv0_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'dec3.decode_conv.conv0.pointwise.bias', (16), 'float32')
        self.dec3_decode_conv_conv0_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec3.decode_conv.conv0.pointwise.weight', (16,16,1,1), 'float32')
        self.dec3_decode_conv_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec3.decode_conv.conv1.depthwise.weight', (16,1,3,3), 'float32')
        self.dec3_decode_conv_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'dec3.decode_conv.conv1.pointwise.bias', (16), 'float32')
        self.dec3_decode_conv_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec3.decode_conv.conv1.pointwise.weight', (16,16,1,1), 'float32')
        self.dec3_upsample_0.bias = self.load_pnnx_bin_as_parameter(archive, 'dec3.upsample.0.bias', (16), 'float32')
        self.dec3_upsample_0.weight = self.load_pnnx_bin_as_parameter(archive, 'dec3.upsample.0.weight', (16,16,1,1), 'float32')
        self.dec3_proj_conv_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec3.proj_conv.depthwise.weight', (16,1,3,3), 'float32')
        self.dec3_proj_conv_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'dec3.proj_conv.pointwise.bias', (16), 'float32')
        self.dec3_proj_conv_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'dec3.proj_conv.pointwise.weight', (16,16,1,1), 'float32')
        self.out0_conv0_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'out0.conv0.depthwise.weight', (16,1,3,3), 'float32')
        self.out0_conv0_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'out0.conv0.pointwise.bias', (16), 'float32')
        self.out0_conv0_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'out0.conv0.pointwise.weight', (16,16,1,1), 'float32')
        self.out0_conv1_depthwise.weight = self.load_pnnx_bin_as_parameter(archive, 'out0.conv1.depthwise.weight', (16,1,3,3), 'float32')
        self.out0_conv1_pointwise.bias = self.load_pnnx_bin_as_parameter(archive, 'out0.conv1.pointwise.bias', (16), 'float32')
        self.out0_conv1_pointwise.weight = self.load_pnnx_bin_as_parameter(archive, 'out0.conv1.pointwise.weight', (16,16,1,1), 'float32')
        self.out1_conv.bias = self.load_pnnx_bin_as_parameter(archive, 'out1.conv.bias', (4), 'float32')
        self.out1_conv.weight = self.load_pnnx_bin_as_parameter(archive, 'out1.conv.weight', (4,16,3,3), 'float32')
        archive.close()

    def load_pnnx_bin_as_parameter(self, archive, key, shape, dtype, requires_grad=True):
        return nn.Parameter(self.load_pnnx_bin_as_tensor(archive, key, shape, dtype), requires_grad)

    def load_pnnx_bin_as_tensor(self, archive, key, shape, dtype):
        fd, tmppath = tempfile.mkstemp()
        with os.fdopen(fd, 'wb') as tmpf, archive.open(key) as keyfile:
            tmpf.write(keyfile.read())
        m = np.memmap(tmppath, dtype=dtype, mode='r', shape=shape).copy()
        os.remove(tmppath)
        return torch.from_numpy(m)

    def forward(self, v_0):
        v_1 = self.conv0_conv(v_0)
        v_2 = self.conv0_relu(v_1)
        v_3 = self.enc1_0_proj_depthwise(v_2)
        v_4 = self.enc1_0_proj_pointwise(v_3)
        v_5 = self.enc1_0_conv1_depthwise(v_2)
        v_6 = self.enc1_0_conv1_pointwise(v_5)
        v_7 = self.enc1_0_conv1_relu(v_6)
        v_8 = self.enc1_0_conv2_depthwise(v_7)
        v_9 = self.enc1_0_conv2_pointwise(v_8)
        v_10 = (v_9 + v_4)
        v_11 = self.enc1_0_relu(v_10)
        v_12 = self.enc1_1_conv1_depthwise(v_11)
        v_13 = self.enc1_1_conv1_pointwise(v_12)
        v_14 = self.enc1_1_conv1_relu(v_13)
        v_15 = self.enc1_1_conv2_depthwise(v_14)
        v_16 = self.enc1_1_conv2_pointwise(v_15)
        v_17 = (v_16 + v_11)
        v_18 = self.enc1_1_relu(v_17)
        v_19 = self.enc2_0_proj_depthwise(v_18)
        v_20 = self.enc2_0_proj_pointwise(v_19)
        v_21 = self.enc2_0_conv1_depthwise(v_18)
        v_22 = self.enc2_0_conv1_pointwise(v_21)
        v_23 = self.enc2_0_conv1_relu(v_22)
        v_24 = self.enc2_0_conv2_depthwise(v_23)
        v_25 = self.enc2_0_conv2_pointwise(v_24)
        v_26 = (v_25 + v_20)
        v_27 = self.enc2_0_relu(v_26)
        v_28 = self.enc2_1_conv1_depthwise(v_27)
        v_29 = self.enc2_1_conv1_pointwise(v_28)
        v_30 = self.enc2_1_conv1_relu(v_29)
        v_31 = self.enc2_1_conv2_depthwise(v_30)
        v_32 = self.enc2_1_conv2_pointwise(v_31)
        v_33 = (v_32 + v_27)
        v_34 = self.enc2_1_relu(v_33)
        v_35 = self.enc3_0_proj_depthwise(v_34)
        v_36 = self.enc3_0_proj_pointwise(v_35)
        v_37 = self.enc3_0_conv1_depthwise(v_34)
        v_38 = self.enc3_0_conv1_pointwise(v_37)
        v_39 = self.enc3_0_conv1_relu(v_38)
        v_40 = self.enc3_0_conv2_depthwise(v_39)
        v_41 = self.enc3_0_conv2_pointwise(v_40)
        v_42 = (v_41 + v_36)
        v_43 = self.enc3_0_relu(v_42)
        v_44 = self.enc3_1_conv1_depthwise(v_43)
        v_45 = self.enc3_1_conv1_pointwise(v_44)
        v_46 = self.enc3_1_conv1_relu(v_45)
        v_47 = self.enc3_1_conv2_depthwise(v_46)
        v_48 = self.enc3_1_conv2_pointwise(v_47)
        v_49 = (v_48 + v_43)
        v_50 = self.enc3_1_relu(v_49)
        v_51 = self.encdec_depthwise(v_50)
        v_52 = self.encdec_pointwise(v_51)
        v_53 = self.encdec_relu(v_52)
        v_54 = self.dec1_decode_conv_conv0_depthwise(v_53)
        v_55 = self.dec1_decode_conv_conv0_pointwise(v_54)
        v_56 = self.dec1_decode_conv_conv0_relu(v_55)
        v_57 = self.dec1_decode_conv_conv1_depthwise(v_56)
        v_58 = self.dec1_decode_conv_conv1_pointwise(v_57)
        v_59 = (v_58 + v_53)
        v_60 = self.dec1_upsample_0(v_59)
        v_61 = self.dec1_upsample_1(v_60)
        v_62 = self.dec1_proj_conv_depthwise(v_34)
        v_63 = self.dec1_proj_conv_pointwise(v_62)
        v_64 = self.dec1_proj_conv_relu(v_63)
        v_65 = (v_61 + v_64)
        v_66 = self.dec2_decode_conv_conv0_depthwise(v_65)
        v_67 = self.dec2_decode_conv_conv0_pointwise(v_66)
        v_68 = self.dec2_decode_conv_conv0_relu(v_67)
        v_69 = self.dec2_decode_conv_conv1_depthwise(v_68)
        v_70 = self.dec2_decode_conv_conv1_pointwise(v_69)
        v_71 = (v_70 + v_65)
        v_72 = self.dec2_upsample_0(v_71)
        v_73 = self.dec2_upsample_1(v_72)
        v_74 = self.dec2_proj_conv_depthwise(v_18)
        v_75 = self.dec2_proj_conv_pointwise(v_74)
        v_76 = self.dec2_proj_conv_relu(v_75)
        v_77 = (v_73 + v_76)
        v_78 = self.dec3_decode_conv_conv0_depthwise(v_77)
        v_79 = self.dec3_decode_conv_conv0_pointwise(v_78)
        v_80 = self.dec3_decode_conv_conv0_relu(v_79)
        v_81 = self.dec3_decode_conv_conv1_depthwise(v_80)
        v_82 = self.dec3_decode_conv_conv1_pointwise(v_81)
        v_83 = (v_82 + v_77)
        v_84 = self.dec3_upsample_0(v_83)
        v_85 = self.dec3_upsample_1(v_84)
        v_86 = self.dec3_proj_conv_depthwise(v_2)
        v_87 = self.dec3_proj_conv_pointwise(v_86)
        v_88 = self.dec3_proj_conv_relu(v_87)
        v_89 = (v_85 + v_88)
        v_90 = self.out0_conv0_depthwise(v_89)
        v_91 = self.out0_conv0_pointwise(v_90)
        v_92 = self.out0_conv0_relu(v_91)
        v_93 = self.out0_conv1_depthwise(v_92)
        v_94 = self.out0_conv1_pointwise(v_93)
        v_95 = (v_94 + v_89)
        v_96 = self.out1_conv(v_95)
        v_97 = (v_0 + v_96)
        return v_97

def export_torchscript():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 4, 1568, 2112, dtype=torch.float)

    mod = torch.jit.trace(net, v_0)
    mod.save("HuanKSigma_pnnx.py.pt")

def export_onnx():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 4, 1568, 2112, dtype=torch.float)

    torch.onnx.export(net, v_0, "HuanKSigma_pnnx.py.onnx", export_params=True, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=13, input_names=['in0'], output_names=['out0'])

def export_pnnx():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 4, 1568, 2112, dtype=torch.float)

    import pnnx
    pnnx.export(net, "HuanKSigma_pnnx.py.pt", v_0)

def export_ncnn():
    export_pnnx()

@torch.no_grad()
def test_inference():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 4, 1568, 2112, dtype=torch.float)

    return net(v_0)

if __name__ == "__main__":
    print(test_inference())
